const fillers = [
  {
    "id": 501,
    "filler_context_f": null,
    "filler_context_m": null,
    "filler_f": "zemřela ho hned po ránu",
    "filler_question_f": null,
    "filler_question_m": null,
    "question_type": null,
    "filler_m": "zemřel ho hned po ránu",
    "filler_right_context": null,
    "filler_right_context_type": null,
    "is_making_sense": "n",
    "was_in_rating": "was",
    "filler_type": "synt",
    "is_filler": "filler",
    "rating_f": 2.09,
    "rating_m": 1.86,
    "rating_all": 1.98
  },
  {
    "id": 502,
    "filler_context_f": null,
    "filler_context_m": null,
    "filler_f": "seděla gauč celé odpoledne",
    "filler_question_f": null,
    "filler_question_m": null,
    "question_type": null,
    "filler_m": "seděl gauč celé odpoledne",
    "filler_right_context": null,
    "filler_right_context_type": null,
    "is_making_sense": "n",
    "was_in_rating": "was",
    "filler_type": "synt",
    "is_filler": "filler",
    "rating_f": 1.48,
    "rating_m": 1.2,
    "rating_all": 1.34
  },
  {
    "id": 503,
    "filler_context_f": null,
    "filler_context_m": null,
    "filler_f": "spala výsledek zkoušky do rána",
    "filler_question_f": null,
    "filler_question_m": null,
    "question_type": null,
    "filler_m": "spal výsledek zkoušky do rána",
    "filler_right_context": null,
    "filler_right_context_type": null,
    "is_making_sense": "n",
    "was_in_rating": "was",
    "filler_type": "synt",
    "is_filler": "filler",
    "rating_f": 1.07,
    "rating_m": 1.13,
    "rating_all": 1.1
  },
  {
    "id": 504,
    "filler_context_f": null,
    "filler_context_m": null,
    "filler_f": "hledala mu celý den bez úspěchu",
    "filler_question_f": null,
    "filler_question_m": null,
    "question_type": null,
    "filler_m": "hledal mu celý den bez úspěchu",
    "filler_right_context": null,
    "filler_right_context_type": null,
    "is_making_sense": "n",
    "was_in_rating": "was",
    "filler_type": "synt",
    "is_filler": "filler",
    "rating_f": 1.19,
    "rating_m": 1.21,
    "rating_all": 1.2
  },
  {
    "id": 505,
    "filler_context_f": null,
    "filler_context_m": null,
    "filler_f": "dívala se na krásnému západ slunce",
    "filler_question_f": null,
    "filler_question_m": null,
    "question_type": null,
    "filler_m": "díval se na krásnému západ slunce",
    "filler_right_context": null,
    "filler_right_context_type": null,
    "is_making_sense": "n",
    "was_in_rating": "was",
    "filler_type": "synt",
    "is_filler": "filler",
    "rating_f": 1,
    "rating_m": 1.31,
    "rating_all": 1.16
  },
  {
    "id": 506,
    "filler_context_f": null,
    "filler_context_m": null,
    "filler_f": "tvrdila mu přišla pozdě tentokrát",
    "filler_question_f": null,
    "filler_question_m": null,
    "question_type": null,
    "filler_m": "tvrdil jí přišel pozdě tentokrát",
    "filler_right_context": null,
    "filler_right_context_type": null,
    "is_making_sense": "n",
    "was_in_rating": "was",
    "filler_type": "synt",
    "is_filler": "filler",
    "rating_f": 1.23,
    "rating_m": 1.57,
    "rating_all": 1.4
  },
  {
    "id": 507,
    "filler_context_f": null,
    "filler_context_m": null,
    "filler_f": "zdálo se jí byl šťastný konec",
    "filler_question_f": null,
    "filler_question_m": null,
    "question_type": null,
    "filler_m": "zdálo se mu byl šťastný konec",
    "filler_right_context": null,
    "filler_right_context_type": null,
    "is_making_sense": "n",
    "was_in_rating": "was",
    "filler_type": "synt",
    "is_filler": "filler",
    "rating_f": 1.32,
    "rating_m": 1.16,
    "rating_all": 1.24
  },
  {
    "id": 508,
    "filler_context_f": null,
    "filler_context_m": null,
    "filler_f": "přiběhla unavený z dlouhé cesty",
    "filler_question_f": null,
    "filler_question_m": null,
    "question_type": null,
    "filler_m": "přiběhl unavená z dlouhé cesty",
    "filler_right_context": null,
    "filler_right_context_type": null,
    "is_making_sense": "n",
    "was_in_rating": "was",
    "filler_type": "synt",
    "is_filler": "filler",
    "rating_f": 1.48,
    "rating_m": 1.67,
    "rating_all": 1.57
  },
  {
    "id": 509,
    "filler_context_f": null,
    "filler_context_m": null,
    "filler_f": "rozbila kus středy o zem",
    "filler_question_f": null,
    "filler_question_m": null,
    "question_type": null,
    "filler_m": "rozbil kus středy o zem",
    "filler_right_context": null,
    "filler_right_context_type": null,
    "is_making_sense": "n",
    "was_in_rating": "was",
    "filler_type": "sem",
    "is_filler": "filler",
    "rating_f": 2,
    "rating_m": 1.85,
    "rating_all": 1.93
  },
  {
    "id": 510,
    "filler_context_f": null,
    "filler_context_m": null,
    "filler_f": "utratila všechen hluk do večera",
    "filler_question_f": null,
    "filler_question_m": null,
    "question_type": null,
    "filler_m": "utratil všechen hluk do večera",
    "filler_right_context": null,
    "filler_right_context_type": null,
    "is_making_sense": "n",
    "was_in_rating": "was",
    "filler_type": "sem",
    "is_filler": "filler",
    "rating_f": 1.44,
    "rating_m": 1.75,
    "rating_all": 1.59
  },
  {
    "id": 511,
    "filler_context_f": null,
    "filler_context_m": null,
    "filler_f": "rozsypala délku po schodech",
    "filler_question_f": null,
    "filler_question_m": null,
    "question_type": null,
    "filler_m": "rozsypal délku po schodech",
    "filler_right_context": null,
    "filler_right_context_type": null,
    "is_making_sense": "n",
    "was_in_rating": "was",
    "filler_type": "sem",
    "is_filler": "filler",
    "rating_f": 1.68,
    "rating_m": 1.88,
    "rating_all": 1.78
  },
  {
    "id": 512,
    "filler_context_f": null,
    "filler_context_m": null,
    "filler_f": "předčítala zelenině pohádky",
    "filler_question_f": "Kdo předčítal pohádky?",
    "filler_question_m": "Kdo předčítal pohádky?",
    "question_type": "open",
    "filler_m": "předčítal zelenině pohádky",
    "filler_right_context": null,
    "filler_right_context_type": null,
    "is_making_sense": "n",
    "was_in_rating": "was",
    "filler_type": "sem",
    "is_filler": "filler",
    "rating_f": 3.55,
    "rating_m": 3.45,
    "rating_all": 3.5
  },
  {
    "id": 513,
    "filler_context_f": null,
    "filler_context_m": null,
    "filler_f": "se vsadila s hřebíkem o pivo",
    "filler_question_f": "Kdo se vsadil o pivo?",
    "filler_question_m": "Kdo se vsadil o pivo?",
    "question_type": "open",
    "filler_m": "se vsadil s hřebíkem o pivo",
    "filler_right_context": null,
    "filler_right_context_type": null,
    "is_making_sense": "n",
    "was_in_rating": "was",
    "filler_type": "sem",
    "is_filler": "filler",
    "rating_f": 2.71,
    "rating_m": 3.27,
    "rating_all": 2.99
  },
  {
    "id": 514,
    "filler_context_f": null,
    "filler_context_m": null,
    "filler_f": "se poradila s kouřem o investicích",
    "filler_question_f": null,
    "filler_question_m": null,
    "question_type": null,
    "filler_m": "se poradil s kouřem o investicích",
    "filler_right_context": null,
    "filler_right_context_type": null,
    "is_making_sense": "n",
    "was_in_rating": "was",
    "filler_type": "sem",
    "is_filler": "filler",
    "rating_f": 2.52,
    "rating_m": 2.7,
    "rating_all": 2.61
  },
  {
    "id": 515,
    "filler_context_f": null,
    "filler_context_m": null,
    "filler_f": "pohladila zákon po hlavě",
    "filler_question_f": null,
    "filler_question_m": null,
    "question_type": null,
    "filler_m": "pohladil zákon po hlavě",
    "filler_right_context": null,
    "filler_right_context_type": null,
    "is_making_sense": "n",
    "was_in_rating": "was",
    "filler_type": "sem",
    "is_filler": "filler",
    "rating_f": 2.27,
    "rating_m": 1.81,
    "rating_all": 2.04
  },
  {
    "id": 516,
    "filler_context_f": null,
    "filler_context_m": null,
    "filler_f": "se vrátila dovnitř protože panika",
    "filler_question_f": null,
    "filler_question_m": null,
    "question_type": null,
    "filler_m": "se vrátil dovnitř protože panika",
    "filler_right_context": null,
    "filler_right_context_type": null,
    "is_making_sense": "y",
    "was_in_rating": "was",
    "filler_type": "because",
    "is_filler": "filler",
    "rating_f": 2.84,
    "rating_m": 3.65,
    "rating_all": 3.24
  },
  {
    "id": 517,
    "filler_context_f": null,
    "filler_context_m": null,
    "filler_f": "si bezstarostně odcestovala protože prázdniny",
    "filler_question_f": null,
    "filler_question_m": null,
    "question_type": null,
    "filler_m": "si bezstarostně odcestoval protože prázdniny",
    "filler_right_context": null,
    "filler_right_context_type": null,
    "is_making_sense": "y",
    "was_in_rating": "was",
    "filler_type": "because",
    "is_filler": "filler",
    "rating_f": 3.86,
    "rating_m": 2.86,
    "rating_all": 3.36
  },
  {
    "id": 518,
    "filler_context_f": null,
    "filler_context_m": null,
    "filler_f": "musela zůstat doma protože chřipka",
    "filler_question_f": null,
    "filler_question_m": null,
    "question_type": null,
    "filler_m": "musel zůstat doma protože chřipka",
    "filler_right_context": null,
    "filler_right_context_type": null,
    "is_making_sense": "y",
    "was_in_rating": "was",
    "filler_type": "because",
    "is_filler": "filler",
    "rating_f": 3.28,
    "rating_m": 3.24,
    "rating_all": 3.26
  },
  {
    "id": 519,
    "filler_context_f": null,
    "filler_context_m": null,
    "filler_f": "už nechtěla psát protože únava",
    "filler_question_f": null,
    "filler_question_m": null,
    "question_type": null,
    "filler_m": "už nechtěl psát protože únava",
    "filler_right_context": null,
    "filler_right_context_type": null,
    "is_making_sense": "y",
    "was_in_rating": "was",
    "filler_type": "because",
    "is_filler": "filler",
    "rating_f": 3.4,
    "rating_m": 3.24,
    "rating_all": 3.32
  },
  {
    "id": 520,
    "filler_context_f": null,
    "filler_context_m": null,
    "filler_f": "musela odejít z práce protože stres",
    "filler_question_f": "Proč odešla [name] z práce?",
    "filler_question_m": "Proč odešel [name] z práce?",
    "question_type": "open",
    "filler_m": "musel odejít z práce protože stres",
    "filler_right_context": null,
    "filler_right_context_type": null,
    "is_making_sense": "y",
    "was_in_rating": "was",
    "filler_type": "because",
    "is_filler": "filler",
    "rating_f": 3.33,
    "rating_m": 3.57,
    "rating_all": 3.45
  },
  {
    "id": 521,
    "filler_context_f": null,
    "filler_context_m": null,
    "filler_f": "se bojí dalšího semestru protože statistika",
    "filler_question_f": "Proč se [name] bojí dalšího semestru?",
    "filler_question_m": "Proč se [name] bojí dalšího semestru?",
    "question_type": "open",
    "filler_m": "se bojí dalšího semestru protože statistika",
    "filler_right_context": null,
    "filler_right_context_type": null,
    "is_making_sense": "y",
    "was_in_rating": "wasnt",
    "filler_type": "because",
    "is_filler": "filler",
    "rating_f": null,
    "rating_m": null,
    "rating_all": null
  },
  {
    "id": 522,
    "filler_context_f": "vůbec nedávala pozor",
    "filler_context_m": "vůbec nedával pozor",
    "filler_f": "rozčílila vedoucí",
    "filler_question_f": "Dávala [name] pozor?",
    "filler_question_m": "Dával [name] pozor?",
    "question_type": "ne",
    "filler_m": "rozčílil vedoucí",
    "filler_right_context": "v nové zasedací místnosti",
    "filler_right_context_type": "place",
    "is_making_sense": "y",
    "was_in_rating": "wasnt",
    "filler_type": "casual",
    "is_filler": "filler",
    "rating_f": null,
    "rating_m": null,
    "rating_all": null
  },
  {
    "id": 523,
    "filler_context_f": "zapomněla na narozeniny svých potkanů",
    "filler_context_m": "zapomněl na narozeniny svých potkanů",
    "filler_f": "ranila jejich city",
    "filler_question_f": "Chovala [name] želvušky?",
    "filler_question_m": "Choval [name] želvušky?",
    "question_type": "ne",
    "filler_m": "ranil jejich city",
    "filler_right_context": "velmi hluboce",
    "filler_right_context_type": "modus",
    "is_making_sense": "y",
    "was_in_rating": "wasnt",
    "filler_type": "casual",
    "is_filler": "filler",
    "rating_f": null,
    "rating_m": null,
    "rating_all": null
  },
  {
    "id": 524,
    "filler_context_f": "celý rok tvrdě nacvičovala kouzelnické představení",
    "filler_context_m": "celý rok tvrdě nacvičoval kouzelnické představení",
    "filler_f": "ohromila publikum",
    "filler_question_f": "Věnovala se [name] tréninku představení?",
    "filler_question_m": "Věnoval se [name] tréninku představení?",
    "question_type": "ano",
    "filler_m": "ohromil publikum",
    "filler_right_context": "v kulturním domě Říp",
    "filler_right_context_type": "modus",
    "is_making_sense": "y",
    "was_in_rating": "wasnt",
    "filler_type": "casual",
    "is_filler": "filler",
    "rating_f": null,
    "rating_m": null,
    "rating_all": null
  },
  {
    "id": 525,
    "filler_context_f": "uprostřed panelové debaty změnila názor",
    "filler_context_m": "uprostřed panelové debaty změnil názor",
    "filler_f": "zmátla ostatní",
    "filler_question_f": "Držela se [name] svého názoru?",
    "filler_question_m": "Držel se [name] svého názoru?",
    "question_type": "ne",
    "filler_m": "zmátl ostatní",
    "filler_right_context": "poměrně výrazně",
    "filler_right_context_type": "modus",
    "is_making_sense": "y",
    "was_in_rating": "wasnt",
    "filler_type": "casual",
    "is_filler": "filler",
    "rating_f": null,
    "rating_m": null,
    "rating_all": null
  },
  {
    "id": 526,
    "filler_context_f": "získala hlavní roli v Prodané nevěstě",
    "filler_context_m": "získal hlavní roli v Prodané nevěstě",
    "filler_f": "se zalekla zodpovědnosti",
    "filler_question_f": "Měla hrát [name] v Othellovi?",
    "filler_question_m": "Měl hrát [name] v Othellovi?",
    "question_type": "ne",
    "filler_m": "se zalekl zodpovědnosti",
    "filler_right_context": "velmi upřímně",
    "filler_right_context_type": "modus",
    "is_making_sense": "y",
    "was_in_rating": "wasnt",
    "filler_type": "casual",
    "is_filler": "filler",
    "rating_f": null,
    "rating_m": null,
    "rating_all": null
  },
  {
    "id": 527,
    "filler_context_f": "nervózně svírala baterku",
    "filler_context_m": "nervózně svíral baterku",
    "filler_f": "se bála tmy",
    "filler_question_f": "Bála se [name] tmy?",
    "filler_question_m": "Bál se [name] tmy?",
    "question_type": "ano",
    "filler_m": "se bál tmy",
    "filler_right_context": "už od dětství",
    "filler_right_context_type": "time",
    "is_making_sense": "y",
    "was_in_rating": "wasnt",
    "filler_type": "casual",
    "is_filler": "filler",
    "rating_f": null,
    "rating_m": null,
    "rating_all": null
  },
  {
    "id": 528,
    "filler_context_f": "nerada dostávala dárky",
    "filler_context_m": "nerad dostával dárky",
    "filler_f": "oslavila výročí",
    "filler_question_f": "Měla [name] ráda dárky?",
    "filler_question_m": "Měl [name] rád dárky?",
    "question_type": "ne",
    "filler_m": "oslavil výročí",
    "filler_right_context": "výletem do hor",
    "filler_right_context_type": "place",
    "is_making_sense": "y",
    "was_in_rating": "wasnt",
    "filler_type": "casual",
    "is_filler": "filler",
    "rating_f": null,
    "rating_m": null,
    "rating_all": null
  },
  {
    "id": 529,
    "filler_context_f": "dostala signál od instruktora",
    "filler_context_m": "dostal signál od instruktora",
    "filler_f": "vyskočila z letadla",
    "filler_question_f": "Kdo vyskočil z letadla?",
    "filler_question_m": "Kdo vyskočil z letadla?",
    "question_type": "open",
    "filler_m": "vyskočil z letadla",
    "filler_right_context": "nad rozlehlými poli",
    "filler_right_context_type": "place",
    "is_making_sense": "y",
    "was_in_rating": "wasnt",
    "filler_type": "casual",
    "is_filler": "filler",
    "rating_f": null,
    "rating_m": null,
    "rating_all": null
  },
  {
    "id": 530,
    "filler_context_f": "málokdy cítila lítost",
    "filler_context_m": "málokdy cítil lítost",
    "filler_f": "zabila moudivláčka",
    "filler_question_f": "Byla [name] nelítostná?",
    "filler_question_m": "Byl [name] nelítostný?",
    "question_type": "ano",
    "filler_m": "zabil moudivláčka",
    "filler_right_context": "bez mrknutí oka",
    "filler_right_context_type": "modus",
    "is_making_sense": "y",
    "was_in_rating": "wasnt",
    "filler_type": "casual",
    "is_filler": "filler",
    "rating_f": null,
    "rating_m": null,
    "rating_all": null
  },
  {
    "id": 531,
    "filler_context_f": "nesouhlasila s postojem vlády",
    "filler_context_m": "nesouhlasil s postojem vlády",
    "filler_f": "se zúčastnila demonstrace",
    "filler_question_f": "Proč [name] demonstrovala?",
    "filler_question_m": "Proč [name] demonstroval?",
    "question_type": "open",
    "filler_m": "se zúčastnil demonstrace",
    "filler_right_context": "před radnicí",
    "filler_right_context_type": "place",
    "is_making_sense": "y",
    "was_in_rating": "wasnt",
    "filler_type": "casual",
    "is_filler": "filler",
    "rating_f": null,
    "rating_m": null,
    "rating_all": null
  },
  {
    "id": 532,
    "filler_context_f": "se zúčastnila lyžařského výcviku",
    "filler_context_m": "se zúčastnil lyžařského výcviku",
    "filler_f": "si zlomila ruku",
    "filler_question_f": "Při čem si [name] nejspíš zlomila ruku?",
    "filler_question_m": "Při čem si [name] nejspíš zlomil ruku?",
    "question_type": "open",
    "filler_m": "si zlomil ruku",
    "filler_right_context": "poměrně ošklivě",
    "filler_right_context_type": "modus",
    "is_making_sense": "y",
    "was_in_rating": "wasnt",
    "filler_type": "casual",
    "is_filler": "filler",
    "rating_f": null,
    "rating_m": null,
    "rating_all": null
  },
  {
    "id": 533,
    "filler_context_f": "potřebovala peníze",
    "filler_context_m": "potřeboval peníze",
    "filler_f": "darovala ledvinu",
    "filler_question_f": "Proč [name] darovala ledvinu?",
    "filler_question_m": "Proč [name] daroval ledvinu?",
    "question_type": "open",
    "filler_m": "daroval ledvinu",
    "filler_right_context": "velmi ochotně",
    "filler_right_context_type": "modus",
    "is_making_sense": "y",
    "was_in_rating": "wasnt",
    "filler_type": "casual",
    "is_filler": "filler",
    "rating_f": null,
    "rating_m": null,
    "rating_all": null
  },
  {
    "id": 534,
    "filler_context_f": "se účastnila schůze oddělení",
    "filler_context_m": "se účastnil schůze oddělení",
    "filler_f": "podala výpověď",
    "filler_question_f": "Kdo podal výpověď?",
    "filler_question_m": "Kdo podal výpověď?",
    "question_type": "open",
    "filler_m": "podal výpověď",
    "filler_right_context": "ihned poté",
    "filler_right_context_type": "time",
    "is_making_sense": "y",
    "was_in_rating": "wasnt",
    "filler_type": "casual",
    "is_filler": "filler",
    "rating_f": null,
    "rating_m": null,
    "rating_all": null
  },
  {
    "id": 535,
    "filler_context_f": "byla svědkem nehody",
    "filler_context_m": "byl svědkem nehody",
    "filler_f": "zavolala sanitku",
    "filler_question_f": "Přivolala [name] pomoc?",
    "filler_question_m": "Přivolal [name] pomoc?",
    "question_type": "ano",
    "filler_m": "zavolal sanitku",
    "filler_right_context": "celkem pohotově",
    "filler_right_context_type": "modus",
    "is_making_sense": "y",
    "was_in_rating": "wasnt",
    "filler_type": "casual",
    "is_filler": "filler",
    "rating_f": null,
    "rating_m": null,
    "rating_all": null
  },
  {
    "id": 536,
    "filler_context_f": "potřebovala získat kredity",
    "filler_context_m": "potřeboval získat kredity",
    "filler_f": "absolvovala experiment",
    "filler_question_f": "Zúčastnila se [name] experimentu?",
    "filler_question_m": "Zúčastnil se [name] experimentu?",
    "question_type": "ano",
    "filler_m": "absolvoval experiment",
    "filler_right_context": "na svém notebooku",
    "filler_right_context_type": "place",
    "is_making_sense": "y",
    "was_in_rating": "wasnt",
    "filler_type": "casual",
    "is_filler": "filler",
    "rating_f": null,
    "rating_m": null,
    "rating_all": null
  },
  {
    "id": 537,
    "filler_context_f": "dostala perfektní přihrávku",
    "filler_context_m": "dostal perfektní přihrávku",
    "filler_f": "dala gól",
    "filler_question_f": "Skórovala [name]?",
    "filler_question_m": "Skóroval [name]?",
    "question_type": "ano",
    "filler_m": "dal gól",
    "filler_right_context": "v poslední třetině",
    "filler_right_context_type": "time",
    "is_making_sense": "y",
    "was_in_rating": "wasnt",
    "filler_type": "casual",
    "is_filler": "filler",
    "rating_f": null,
    "rating_m": null,
    "rating_all": null
  },
  {
    "id": 538,
    "filler_context_f": "byla strašlivě unavená",
    "filler_context_m": "byl strašlivě unavený",
    "filler_f": "si vyčistila zuby",
    "filler_question_f": "Použila [name] kartáček?",
    "filler_question_m": "Použil [name] kartáček?",
    "question_type": "ano",
    "filler_m": "si vyčistil zuby",
    "filler_right_context": "cizím kartáčkem",
    "filler_right_context_type": "modus",
    "is_making_sense": "y",
    "was_in_rating": "wasnt",
    "filler_type": "casual",
    "is_filler": "filler",
    "rating_f": null,
    "rating_m": null,
    "rating_all": null
  },
  {
    "id": 539,
    "filler_context_f": "se cítila sama",
    "filler_context_m": "se cítil sám",
    "filler_f": "adoptovala leguána",
    "filler_question_f": "Koho adoptovala [name]?",
    "filler_question_m": "Koho adoptoval [name]?",
    "question_type": "open",
    "filler_m": "adoptoval leguána",
    "filler_right_context": "z místní zoo",
    "filler_right_context_type": "place",
    "is_making_sense": "y",
    "was_in_rating": "wasnt",
    "filler_type": "casual",
    "is_filler": "filler",
    "rating_f": null,
    "rating_m": null,
    "rating_all": null
  },
  {
    "id": 540,
    "filler_context_f": "zjistila cenu filtrované kávy ve Vršovicích",
    "filler_context_m": "zjistil cenu filtrované kávy ve Vršovicích",
    "filler_f": "prodělala šok",
    "filler_question_f": "Jakou kávu si pravděpodobně chtěla dát [name]?",
    "filler_question_m": "Jakou kávu si pravděpodobně chtěl dát [name]?",
    "question_type": "open",
    "filler_m": "prodělal šok",
    "filler_right_context": "docela nepokrytě",
    "filler_right_context_type": "modus",
    "is_making_sense": "y",
    "was_in_rating": "wasnt",
    "filler_type": "casual",
    "is_filler": "filler",
    "rating_f": null,
    "rating_m": null,
    "rating_all": null
  },
  {
    "id": 541,
    "filler_context_f": "zpozorovala kočičí chlupy všude kolem",
    "filler_context_m": "zpozoroval kočičí chlupy všude kolem",
    "filler_f": "učesala koberec",
    "filler_question_f": "Měla [name] koberec v kuchyni?",
    "filler_question_m": "Měl [name] koberec v kuchyni?",
    "question_type": "ano",
    "filler_m": "učesal koberec",
    "filler_right_context": "v kuchyni",
    "filler_right_context_type": "place",
    "is_making_sense": "y",
    "was_in_rating": "wasnt",
    "filler_type": "casual",
    "is_filler": "filler",
    "rating_f": null,
    "rating_m": null,
    "rating_all": null
  },
  {
    "id": 542,
    "filler_context_f": "plánovala svatbu na zahradě",
    "filler_context_m": "plánoval svatbu na zahradě",
    "filler_f": "šlápla na hrábě",
    "filler_question_f": "Kde plánovala [name] svatbu?",
    "filler_question_m": "Kde plánoval [name] svatbu?",
    "question_type": "open",
    "filler_m": "šlápl na hrábě",
    "filler_right_context": "během obhlídky",
    "filler_right_context_type": "time",
    "is_making_sense": "y",
    "was_in_rating": "wasnt",
    "filler_type": "casual",
    "is_filler": "filler",
    "rating_f": null,
    "rating_m": null,
    "rating_all": null
  },
  {
    "id": 543,
    "filler_context_f": "spatřila na pláži cosi uvězněného v síti",
    "filler_context_m": "spatřil na pláži cosi uvězněného v síti",
    "filler_f": "zachránila tuleně",
    "filler_question_f": "Koho zachránila [name]?",
    "filler_question_m": "Koho zachránil [name]?",
    "question_type": "open",
    "filler_m": "zachránil tuleně",
    "filler_right_context": "velmi obratně",
    "filler_right_context_type": "modus",
    "is_making_sense": "y",
    "was_in_rating": "wasnt",
    "filler_type": "casual",
    "is_filler": "filler",
    "rating_f": null,
    "rating_m": null,
    "rating_all": null
  },
  {
    "id": 544,
    "filler_context_f": "vítala každou možnost prokrastinace",
    "filler_context_m": "vítal každou možnost prokrastinace",
    "filler_f": "vynesla odpadky",
    "filler_question_f": "Kam vynesla [name] odpadky?",
    "filler_question_m": "Kam vynesl [name] odpadky?",
    "question_type": "open",
    "filler_m": "vynesl odpadky",
    "filler_right_context": "do sběrného dvora",
    "filler_right_context_type": "place",
    "is_making_sense": "y",
    "was_in_rating": "wasnt",
    "filler_type": "casual",
    "is_filler": "filler",
    "rating_f": null,
    "rating_m": null,
    "rating_all": null
  },
  {
    "id": 545,
    "filler_context_f": "si koupila patnáct lístků",
    "filler_context_m": "si koupil patnáct lístků",
    "filler_f": "vyhrála tombolu",
    "filler_question_f": "Kolik lístků si koupila [name]?",
    "filler_question_m": "Kolik lístků si koupil [name]?",
    "question_type": "open",
    "filler_m": "vyhrál tombolu",
    "filler_right_context": "na hasičském plese",
    "filler_right_context_type": "place",
    "is_making_sense": "y",
    "was_in_rating": "wasnt",
    "filler_type": "casual",
    "is_filler": "filler",
    "rating_f": null,
    "rating_m": null,
    "rating_all": null
  },
  {
    "id": 546,
    "filler_context_f": "si důrazně odkašlala",
    "filler_context_m": "si důrazně odkašlal",
    "filler_f": "oznámila novinku",
    "filler_question_f": null,
    "filler_question_m": null,
    "question_type": null,
    "filler_m": "oznámil novinku",
    "filler_right_context": "vcelku teatrálně",
    "filler_right_context_type": null,
    "is_making_sense": "y",
    "was_in_rating": "wasnt",
    "filler_type": "casual",
    "is_filler": "filler",
    "rating_f": null,
    "rating_m": null,
    "rating_all": null
  },
  {
    "id": 547,
    "filler_context_f": "si nedala pozor na alergeny",
    "filler_context_m": "si nedal pozor na alergeny",
    "filler_f": "se zmítala v křečích",
    "filler_question_f": "Proč měla [name] křeče?",
    "filler_question_m": "Proč měl [name] křeče?",
    "question_type": "open",
    "filler_m": "se zmítal v křečích",
    "filler_right_context": "v restauraci na nábřeží",
    "filler_right_context_type": "place",
    "is_making_sense": "y",
    "was_in_rating": "wasnt",
    "filler_type": "casual",
    "is_filler": "filler",
    "rating_f": null,
    "rating_m": null,
    "rating_all": null
  },
  {
    "id": 548,
    "filler_context_f": "se chystala vyměnit baterie",
    "filler_context_m": "se chystal vyměnit baterie",
    "filler_f": "vyplivla žvejkačku",
    "filler_question_f": "Co vyplivla [name]?",
    "filler_question_m": "Co vyplivl [name]?",
    "question_type": "open",
    "filler_m": "vyplivl žvejkačku",
    "filler_right_context": "na zem",
    "filler_right_context_type": "place",
    "is_making_sense": "n",
    "was_in_rating": "wasnt",
    "filler_type": "casual",
    "is_filler": "filler",
    "rating_f": null,
    "rating_m": null,
    "rating_all": null
  },
  {
    "id": 549,
    "filler_context_f": "odmítala dál nečinně přihlížet",
    "filler_context_m": "odmítal dál nečinně přihlížet",
    "filler_f": "vyšroubovala žárovku",
    "filler_question_f": "Kdo odmítal dál přihlížet?",
    "filler_question_m": "Kdo odmítal dál přihlížet?",
    "question_type": "open",
    "filler_m": "vyšrouboval žárovku",
    "filler_right_context": "z lustru v pokoji",
    "filler_right_context_type": null,
    "is_making_sense": "n",
    "was_in_rating": "wasnt",
    "filler_type": "casual",
    "is_filler": "filler",
    "rating_f": null,
    "rating_m": null,
    "rating_all": null
  },
  {
    "id": 550,
    "filler_context_f": "utonula v lipách",
    "filler_context_m": "utonul v lipách",
    "filler_f": "vykašlala bicykl",
    "filler_question_f": null,
    "filler_question_m": null,
    "question_type": null,
    "filler_m": "vykašlal bicykl",
    "filler_right_context": "mezi rty",
    "filler_right_context_type": "place",
    "is_making_sense": "n",
    "was_in_rating": "wasnt",
    "filler_type": "casual",
    "is_filler": "filler",
    "rating_f": null,
    "rating_m": null,
    "rating_all": null
  },
  {
    "id": 551,
    "filler_context_f": "zabředla příliš do sena",
    "filler_context_m": "zabředl příliš do sena",
    "filler_f": "uslyšela zelenou",
    "filler_question_f": null,
    "filler_question_m": null,
    "question_type": null,
    "filler_m": "uslyšel zelenou",
    "filler_right_context": "poměrně pikantně",
    "filler_right_context_type": null,
    "is_making_sense": "n",
    "was_in_rating": "wasnt",
    "filler_type": "casual",
    "is_filler": "filler",
    "rating_f": null,
    "rating_m": null,
    "rating_all": null
  },
  {
    "id": 552,
    "filler_context_f": "nikomu stud nedarovala",
    "filler_context_m": "nikomu stud nedaroval",
    "filler_f": "odšpuntovala izolepu",
    "filler_question_f": null,
    "filler_question_m": null,
    "question_type": null,
    "filler_m": "odšpuntoval izolepu",
    "filler_right_context": "levou zadní",
    "filler_right_context_type": null,
    "is_making_sense": "n",
    "was_in_rating": "wasnt",
    "filler_type": "casual",
    "is_filler": "filler",
    "rating_f": null,
    "rating_m": null,
    "rating_all": null
  },
  {
    "id": 553,
    "filler_context_f": "rozbila stan",
    "filler_context_m": "rozbil stan",
    "filler_f": "vdechla inflaci",
    "filler_question_f": null,
    "filler_question_m": null,
    "question_type": null,
    "filler_m": "vdechl inflaci",
    "filler_right_context": "pěkně do plic",
    "filler_right_context_type": null,
    "is_making_sense": "n",
    "was_in_rating": "wasnt",
    "filler_type": "casual",
    "is_filler": "filler",
    "rating_f": null,
    "rating_m": null,
    "rating_all": null
  },
  {
    "id": 554,
    "filler_context_f": "usrkla trochu rosy",
    "filler_context_m": "usrkl trochu rosy",
    "filler_f": "vypáčila kapesník",
    "filler_question_f": null,
    "filler_question_m": null,
    "question_type": null,
    "filler_m": "vypáčil kapesník",
    "filler_right_context": "z ucha jehly",
    "filler_right_context_type": null,
    "is_making_sense": "n",
    "was_in_rating": "wasnt",
    "filler_type": "casual",
    "is_filler": "filler",
    "rating_f": null,
    "rating_m": null,
    "rating_all": null
  },
  {
    "id": 555,
    "filler_context_f": null,
    "filler_context_m": null,
    "filler_f": "získala stipendium",
    "filler_question_f": "Na jak dlouho získala [name] stipendium?",
    "filler_question_m": "Na jak dlouho získal [name] stipendium?",
    "question_type": "open",
    "filler_m": "získal stipendium",
    "filler_right_context": "na dva roky",
    "filler_right_context_type": "time",
    "is_making_sense": "y",
    "was_in_rating": "wasnt",
    "filler_type": "single",
    "is_filler": "filler",
    "rating_f": null,
    "rating_m": null,
    "rating_all": null
  },
  {
    "id": 556,
    "filler_context_f": null,
    "filler_context_m": null,
    "filler_f": "stihla autobus",
    "filler_question_f": "Čím jela [name]?",
    "filler_question_m": "Čím jel [name]?",
    "question_type": "open",
    "filler_m": "stihl autobus",
    "filler_right_context": "z Kačerova",
    "filler_right_context_type": "place",
    "is_making_sense": "y",
    "was_in_rating": "wasnt",
    "filler_type": "single",
    "is_filler": "filler",
    "rating_f": null,
    "rating_m": null,
    "rating_all": null
  },
  {
    "id": 557,
    "filler_context_f": null,
    "filler_context_m": null,
    "filler_f": "zmokla v lese",
    "filler_question_f": "Kde zmokla [name]?",
    "filler_question_m": "Kde zmokl [name]?",
    "question_type": "open",
    "filler_m": "zmokl v lese",
    "filler_right_context": "na Šumavě",
    "filler_right_context_type": "place",
    "is_making_sense": "y",
    "was_in_rating": "wasnt",
    "filler_type": "single",
    "is_filler": "filler",
    "rating_f": null,
    "rating_m": null,
    "rating_all": null
  },
  {
    "id": 558,
    "filler_context_f": null,
    "filler_context_m": null,
    "filler_f": "souhlasila s návrhem",
    "filler_question_f": null,
    "filler_question_m": null,
    "question_type": null,
    "filler_m": "souhlasil s návrhem",
    "filler_right_context": "trochu proti své vůli",
    "filler_right_context_type": null,
    "is_making_sense": "y",
    "was_in_rating": "wasnt",
    "filler_type": "single",
    "is_filler": "filler",
    "rating_f": null,
    "rating_m": null,
    "rating_all": null
  },
  {
    "id": 559,
    "filler_context_f": null,
    "filler_context_m": null,
    "filler_f": "si ochočila tamagoči",
    "filler_question_f": null,
    "filler_question_m": null,
    "question_type": null,
    "filler_m": "si ochočil tamagoči",
    "filler_right_context": "docela rychle",
    "filler_right_context_type": null,
    "is_making_sense": "y",
    "was_in_rating": "wasnt",
    "filler_type": "single",
    "is_filler": "filler",
    "rating_f": null,
    "rating_m": null,
    "rating_all": null
  },
  {
    "id": 560,
    "filler_context_f": null,
    "filler_context_m": null,
    "filler_f": "vyjádřila pochybnosti",
    "filler_question_f": null,
    "filler_question_m": null,
    "question_type": null,
    "filler_m": "vyjádřil pochybnosti",
    "filler_right_context": "trochu neurvale",
    "filler_right_context_type": null,
    "is_making_sense": "y",
    "was_in_rating": "wasnt",
    "filler_type": "single",
    "is_filler": "filler",
    "rating_f": null,
    "rating_m": null,
    "rating_all": null
  },
  {
    "id": 561,
    "filler_context_f": null,
    "filler_context_m": null,
    "filler_f": "prozradila tajemství",
    "filler_question_f": null,
    "filler_question_m": null,
    "question_type": null,
    "filler_m": "prozradil tajemství",
    "filler_right_context": "během výletu",
    "filler_right_context_type": null,
    "is_making_sense": "y",
    "was_in_rating": "wasnt",
    "filler_type": "single",
    "is_filler": "filler",
    "rating_f": null,
    "rating_m": null,
    "rating_all": null
  },
  {
    "id": 562,
    "filler_context_f": null,
    "filler_context_m": null,
    "filler_f": "vyhrožovala starostovi",
    "filler_question_f": null,
    "filler_question_m": null,
    "question_type": null,
    "filler_m": "vyhrožoval starostovi",
    "filler_right_context": "velmi přesvědčivě",
    "filler_right_context_type": null,
    "is_making_sense": "y",
    "was_in_rating": "wasnt",
    "filler_type": "single",
    "is_filler": "filler",
    "rating_f": null,
    "rating_m": null,
    "rating_all": null
  },
  {
    "id": 563,
    "filler_context_f": null,
    "filler_context_m": null,
    "filler_f": "si nasadila sluchátka",
    "filler_question_f": null,
    "filler_question_m": null,
    "question_type": null,
    "filler_m": "si nasadil sluchátka",
    "filler_right_context": "trochu nespolečensky",
    "filler_right_context_type": null,
    "is_making_sense": "y",
    "was_in_rating": "wasnt",
    "filler_type": "single",
    "is_filler": "filler",
    "rating_f": null,
    "rating_m": null,
    "rating_all": null
  },
  {
    "id": 564,
    "filler_context_f": null,
    "filler_context_m": null,
    "filler_f": "ignorovala předpověď počasí",
    "filler_question_f": null,
    "filler_question_m": null,
    "question_type": null,
    "filler_m": "ignoroval předpověď počasí",
    "filler_right_context": "příliš lehkovážně",
    "filler_right_context_type": null,
    "is_making_sense": "y",
    "was_in_rating": "wasnt",
    "filler_type": "single",
    "is_filler": "filler",
    "rating_f": null,
    "rating_m": null,
    "rating_all": null
  },
  {
    "id": 565,
    "filler_context_f": null,
    "filler_context_m": null,
    "filler_f": "chytila neštovice",
    "filler_question_f": "Čím se nakazila [name]?",
    "filler_question_m": "Čím se nakazil [name]?",
    "question_type": "open",
    "filler_m": "chytil neštovice",
    "filler_right_context": "v dětské skupince",
    "filler_right_context_type": "place",
    "is_making_sense": "y",
    "was_in_rating": "wasnt",
    "filler_type": "single",
    "is_filler": "filler",
    "rating_f": null,
    "rating_m": null,
    "rating_all": null
  },
  {
    "id": 566,
    "filler_context_f": null,
    "filler_context_m": null,
    "filler_f": "macerovala implantát v dračí krvi",
    "filler_question_f": "Co dělala [name]?",
    "filler_question_m": "Co dělal [name]?",
    "question_type": "open",
    "filler_m": "maceroval implantát v dračí krvi",
    "filler_right_context": "v noci na zahradě",
    "filler_right_context_type": "time-place",
    "is_making_sense": "y",
    "was_in_rating": "wasnt",
    "filler_type": "single",
    "is_filler": "filler",
    "rating_f": null,
    "rating_m": null,
    "rating_all": null
  },
  {
    "id": 567,
    "filler_context_f": null,
    "filler_context_m": null,
    "filler_f": "si nechávala věštit osud z dlaně",
    "filler_question_f": "Nechávala si [name] věštit z kávové sedliny?",
    "filler_question_m": "Nechával si [name] věštit z kávové sedliny?",
    "question_type": "ne",
    "filler_m": "si nechával věštit osud z dlaně",
    "filler_right_context": "docela pravidelně",
    "filler_right_context_type": "modus",
    "is_making_sense": "y",
    "was_in_rating": "wasnt",
    "filler_type": "single",
    "is_filler": "filler",
    "rating_f": null,
    "rating_m": null,
    "rating_all": null
  },
  {
    "id": 568,
    "filler_context_f": null,
    "filler_context_m": null,
    "filler_f": "prochrněla den",
    "filler_question_f": "Prospala [name] celý den na půdě?",
    "filler_question_m": "Prospal [name] celý den na půdě?",
    "question_type": "ne",
    "filler_m": "prochrněl den",
    "filler_right_context": "v jednom sklepu",
    "filler_right_context_type": "place",
    "is_making_sense": "y",
    "was_in_rating": "wasnt",
    "filler_type": "single",
    "is_filler": "filler",
    "rating_f": null,
    "rating_m": null,
    "rating_all": null
  },
  {
    "id": 569,
    "filler_context_f": null,
    "filler_context_m": null,
    "filler_f": "venčila králíka",
    "filler_question_f": "Koho venčila [name]?",
    "filler_question_m": "Koho venčil [name]?",
    "question_type": "open",
    "filler_m": "venčil králíka",
    "filler_right_context": "ve Stromovce",
    "filler_right_context_type": "place",
    "is_making_sense": "y",
    "was_in_rating": "wasnt",
    "filler_type": "single",
    "is_filler": "filler",
    "rating_f": null,
    "rating_m": null,
    "rating_all": null
  },
  {
    "id": 570,
    "filler_context_f": null,
    "filler_context_m": null,
    "filler_f": "se vydala cestou špendlíků",
    "filler_question_f": "Kam se vydala [name]?",
    "filler_question_m": "Kam se vydal [name]?",
    "question_type": "open",
    "filler_m": "se vydal cestou špendlíků",
    "filler_right_context": "zpátky domů",
    "filler_right_context_type": "place",
    "is_making_sense": "n",
    "was_in_rating": "wasnt",
    "filler_type": "single",
    "is_filler": "filler",
    "rating_f": null,
    "rating_m": null,
    "rating_all": null
  }
]
